import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :portfolio, PortfolioWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Redirection systematique vers HTTPS, avec HSTS.
#
# Cette option DOIT etre posee a la compilation et non dans `runtime.exs` :
# `force_ssl` fait partie des cles que l'endpoint Phoenix marque comme
# `compile_env`. Une valeur posee au demarrage qui differe de celle compilee
# fait AVORTER le boot de la release, avec le message « has a different value
# set for path [:force_ssl] ... during runtime compared to compile time ».
# C'est ce qui a empeche le premier deploiement d'aboutir.
#
# Le mandataire termine TLS et transmet `x-forwarded-proto`, que l'endpoint
# lit grace a `forward_headers` : il n'y a donc pas de boucle de redirection.
# L'exclusion porte sur le CHEMIN `/health`, celui que le mandataire interroge
# (cf. `config/deploy.yml`, `proxy.healthcheck.path`), et surtout PAS sur
# l'en-tete Host. Un Host se falsifie trivialement depuis n'importe ou :
# exclure `localhost` permettrait a quiconque de contourner la redirection
# HTTPS en le declarant. Le chemin borne l'exclusion au strict necessaire.
#
# Sans cette exclusion, le mandataire interroge l'application en clair sur le
# reseau des conteneurs, recoit une redirection vers https://thibaultsan.com,
# la suit, et echoue faute de certificat, lequel ne sera emis que lorsque
# l'application sera declaree saine. Le deploiement ne peut jamais aboutir.
#
# `rewrite_on` fait lire l'en-tete pose par le mandataire, sans quoi toute
# requete legitime serait vue comme non chiffree et redirigee en boucle.
config :portfolio, PortfolioWeb.Endpoint,
  force_ssl: [
    hsts: true,
    rewrite_on: [:x_forwarded_proto],
    exclude: [paths: ["/health"]]
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Portfolio.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
