name: CI
on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]
permissions:
  contents: read
env:
  SHELL: /bin/bash
  DOCKER_IMAGE: "thibaultsan/portfolio"
jobs:
  tools:
    name: TOOLS
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3

  lint:
    name: LINT
    needs: [tools]
    runs-on: ubuntu-24.04
    env:
      MIX_ENV: dev
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ env.MIX_ENV }}-mise-${{ hashFiles('**/.tool-versions') }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ env.MIX_ENV }}-mise-${{ hashFiles('**/.tool-versions') }}-mix-
            ${{ env.MIX_ENV }}-mise-
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --dry-run --check-formatted
      - run: mix deps.unlock --check-unused
      - run: mix hex.audit
      - run: mix deps.audit
      - run: mix credo --strict
      - run: mix sobelow --config
      - uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "table"
          scanners: "vuln,misconfig,license"
          exit-code: "1"
          ignore-unfixed: true
          skip-dirs: _build
          severity: "CRITICAL,HIGH"

  test:
    name: TEST
    needs: [tools]
    runs-on: ubuntu-24.04
    env:
      MIX_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/portfolio_test
    services:
      postgres:
        image: postgis/postgis:17-3.5-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: portfolio_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ env.MIX_ENV }}-mise-${{ hashFiles('**/.tool-versions') }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ env.MIX_ENV }}-mise-${{ hashFiles('**/.tool-versions') }}-mix-
            ${{ env.MIX_ENV }}-mise-
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix test --max-failures=1 --color

  build:
    name: BUILD
    needs: [lint, test]
    runs-on: ubuntu-24.04
    env:
      MIX_ENV: prod
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ env.MIX_ENV }}-mise-${{ hashFiles('**/.tool-versions') }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ env.MIX_ENV }}-mise-${{ hashFiles('**/.tool-versions') }}-mix-
            ${{ env.MIX_ENV }}-mise-
      - run: mix deps.get --only prod
      - run: mix do assets.setup + compile --warnings-as-errors + assets.deploy + release --overwrite
      - uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t image:${{ github.sha }} .
      - uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: "image:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
      - name: Docker meta
        if: ${{ contains(github.ref, 'refs/tags/') }}
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest
      - name: Login to Docker Hub
        if: ${{ contains(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        if: ${{ contains(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
